
"""
Static dictionary containing all supported resources + actions
- Keys are the boto3 client names
- Values are the list of supported actions for the client
"""
RESOURCE_ACTIONS = {
    'EC2':[
        "OUTDATED_EBS_SNAPSHOTS",
        "UNDERUTILIZED_EC2_INSTANCES",
        "IDLE_EC2_INSTANCES",
        "UNATTACHED_EC2_VOLUMES",
        "UNENCRYPTED_EC2_VOLUMES",
        "EXPIRING_EC2_RESERVED_INSTANCES",
        "PREVIOUS_GEN_EC2_INSTANCES",
        "UNATTACHED_ELASTIC_IPS",
        "PREVIOUS_GEN_EC2_VOLUMES",
        "OLD_STOPPED_EC2_INSTANCES",
        "IO_VOLUME_TYPE_NON_OPTIMIZED",
        "UNUSED_SECURITY_GROUPS",
    ],
    'RDS':[
        "IDLE_RDS_INSTANCES",
        "UNDERUTILIZED_RDS_INSTANCES",
        "UNENCRYPTED_RDS_INSTANCES",
        "PREVIOUS_GEN_RDS_INSTANCES",
    ],
    'ELBV2':[
        "IDLE_APPLICATION_LOAD_BALANCERS",
    ],
    'IAM':[
        "INACTIVE_IAM_ROLES",
        "EXPIRED_IAM_KEYS",
    ],
    'Elasticache':[
        "OLD_ON_DEMAND_ELASTICACHE",
    ],
    'COST-OPTIMIZATION-HUB':[
        "COST_OPTIMIZATION_HUB_RECOMMENDATIONS",
    ],
    # 'CE':[
    #     "RESERVED_INSTANCE_RECOMMENDATIONS",
    # ],
    'SERVICE-QUOTAS':[
        "CRITICAL_SERVICE_QUOTAS",
    ],
    'COMPUTE-OPTIMIZER':[
        "LAMBDA_RIGHTSIZE_MEMORY",
        "EBS_RIGHTSIZE_VOLUME_TYPE",
        "EBS_RIGHTSIZE_VOLUME_IOPS",
        "EBS_RIGHTSIZE_VOLUME_SIZE",
        "RDS_CPU_OVERPROVISIONED",
        "RDS_CPU_UNDERPROVISIONED",
        "RDS_NEW_ENGINE_VERSION_AVAILABLE",
        "RDS_NEW_GENERATION_INSTANCE_CLASS_AVAILABLE",
        "RDS_NETWORK_BANDWIDTH_OVERPROVISIONED",
        "RDS_NETWORK_BANDWIDTH_UNDERPROVISIONED",
        "RDS_EBS_THROUGHPUT_OVERPROVISIONED",
        "RDS_EBS_THROUGHPUT_UNDERPROVISIONED",
        "RDS_EBS_IOPS_OVERPROVISIONED",
        "RDS_EBS_NEW_GENERATION_STORAGE_TYPE_AVAILABLE",
        "RDS_EBS_VOLUME_ALLOCATED_STORAGE_UNDERPROVISIONED",
        "ECS4FARGATE_CPU_OVERPROVISIONED",
        "ECS4FARGATE_CPU_UNDERPROVISIONED",
        "ECS4FARGATE_MEMORY_OVERPROVISIONED",
        "ECS4FARGATE_MEMORY_UNDERPROVISIONED",
        "ASG_NOT_OPTIMIZED",
        "EC2_CPU_OVERPROVISIONED",
        "EC2_CPU_UNDERPROVISIONED",
        "EC2_MEMORY_OVERPROVISIONED",
        "EC2_MEMORY_UNDERPROVISIONED",
        "EC2_NETWORK_BANDWIDTH_OVERPROVISIONED",
        "EC2_NETWORK_BANDWIDTH_UNDERPROVISIONED",
        "EC2_NETWORK_PPS_OVERPROVISIONED",
        "EC2_NETWORK_PPS_UNDERPROVISIONED",
        "EC2_LICENSE_NOT_OPTIMIZED",
    ],
}